In [14]:
import pandas as pd

In [16]:
df = pd.read_csv("C:\\Users\\Zohaib\\Downloads\\data.csv")

In [17]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

# Basic Data Exploration #

In [18]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [19]:
df.tail()

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [20]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [21]:
df.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [22]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [23]:
df["Pulse"].max()

np.int64(130)

In [24]:
df["Duration"].min()

np.int64(30)

In [25]:
df["Calories"].mean()

np.float64(304.68)

 # Data Cleaning #

In [28]:
df["Date"]= pd.to_datetime(df["Date"],format="mixed")

In [29]:
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [30]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [31]:
df["Calories"].fillna(df["Calories"].mean(), inplace=True)

C:\Users\Zohaib\AppData\Local\Temp\ipykernel_11440\1871284254.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Calories"].fillna(df["Calories"].mean(), inplace=True)

In [33]:
df.duplicated().sum()

np.int64(1)

In [37]:
df.drop_duplicates(inplace=True)

In [38]:
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7        450 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
22        45        NaT    100       119    282.00
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

In [40]:
df[df["Duration"]> 60]

   Duration       Date  Pulse  Maxpulse  Calories
7       450 2020-12-08    104       134     253.3

In [41]:
df.loc[df['Duration']>120,'Duration']=60

In [42]:
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         60 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
22        45        NaT    100       119    282.00
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

In [43]:
df.dropna(subset=["Date"],inplace=True)

In [44]:
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         60 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

# Data Selection Tasks #

In [47]:
df[df["Duration"]>60]

Empty DataFrame
Columns: [Duration, Date, Pulse, Maxpulse, Calories]
Index: []

In [48]:
df[df["Pulse"]>110]

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
4         45 2020-12-05    117       148     406.0
23        60 2020-12-23    130       101     300.0

In [49]:
df[df["Calories"]>350]

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
4         45 2020-12-05    117       148     406.0
6         60 2020-12-07    110       136     374.0
14        60 2020-12-14    104       132     379.3
21        60 2020-12-21    108       131     364.2
30        60 2020-12-30    102       129     380.3

In [58]:
df[(df['Pulse']<=110) & (df['Pulse']>=100)]

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         60 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
17        60 2020-12-17    100       120    300.00
19        60 2020-12-19    103       123    323.00
21        60 2020-12-21    108       131    364.20
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30

In [62]:
df[['Duration','Calories']]

    Duration  Calories
0         60    409.10
1         60    479.00
2         60    340.00
3         45    282.40
4         45    406.00
5         60    300.00
6         60    374.00
7         60    253.30
8         30    195.10
9         60    269.00
10        60    329.30
11        60    250.70
13        60    345.30
14        60    379.30
15        60    275.00
16        60    215.20
17        60    300.00
18        45    304.68
19        60    323.00
20        45    243.00
21        60    364.20
23        60    300.00
24        45    246.00
25        60    334.50
26        60    250.00
27        60    241.00
28        60    304.68
29        60    280.00
30        60    380.30
31        60    243.00

# Data Analysis Tasks #

In [64]:
df["Pulse"].mean()

np.float64(103.73333333333333)

In [69]:
df.loc[df["Calories"].idxmax()]

Duration                     60
Date        2020-12-02 00:00:00
Pulse                       117
Maxpulse                    145
Calories                  479.0
Name: 1, dtype: object

In [70]:
df["Calories"].sum()

np.float64(9217.06)

In [71]:
df["Duration"].mean()

np.float64(56.5)

In [72]:
df.loc[df["Maxpulse"].idxmax()]

Duration                     45
Date        2020-12-04 00:00:00
Pulse                       109
Maxpulse                    175
Calories                  282.4
Name: 3, dtype: object

# Sorting & Grouping Tasks #