In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:\\Users\\Zohaib\\Downloads\\sales.csv")

In [3]:
df

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

# Data Reading Tasks #

In [4]:
df.head(8)

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
5,6,2024-07-07,West,Laptop,Electronics,New,8,1480,0.01,11721.60
6,7,2024-01-21,East,Mouse,Accessories,Returning,6,137,0.27,600.06
7,8,2024-04-12,West,Phone,Accessories,Returning,5,1117,0.26,4132.90

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    int64
 1   date           500 non-null    object
 2   region         500 non-null    object
 3   product        500 non-null    object
 4   category       500 non-null    object
 5   customer_type  500 non-null    object
 6   quantity       500 non-null    int64
 7   price          500 non-null    int64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: float64(2), int64(3), object(5)
memory usage: 39.2+ KB

In [6]:
df.describe()

         order_id    quantity        price   discount         sales
count  500.000000  500.000000   500.000000  500.00000    500.000000
mean   250.500000    4.968000   768.158000    0.14666   3333.059560
std    144.481833    2.569081   404.010497    0.08612   2693.185995
min      1.000000    1.000000    50.000000    0.00000     67.320000
25%    125.750000    3.000000   432.750000    0.08000   1120.867500
50%    250.500000    5.000000   742.000000    0.15000   2582.805000
75%    375.250000    7.000000  1094.500000    0.22000   4998.030000
max    500.000000    9.000000  1499.000000    0.30000  12700.800000

In [7]:
df.columns

Index(['order_id', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'discount', 'sales'],
      dtype='object')

In [8]:
df.rename(columns={'order_id': 'OrderID'}, inplace=True)

In [9]:
df

,OrderID,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

# Data Cleaning Tasks #

In [10]:
df.isnull().sum()

OrderID          0
date             0
region           0
product          0
category         0
customer_type    0
quantity         0
price            0
discount         0
sales            0
dtype: int64

In [11]:
df.dropna(inplace=True)

In [12]:
df

,OrderID,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [13]:
df['price'].fillna(df['price'].mean(), inplace=True)

C:\Users\Zohaib\AppData\Local\Temp\ipykernel_16916\1085838478.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['price'].fillna(df['price'].mean(), inplace=True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df

,OrderID,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [17]:
df['date'] = pd.to_datetime(df['date'])

In [18]:
df

,OrderID,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [19]:
df['date'].dt.year
df['date'].dt.month

0       4
1      12
2       9
3       4
4       3
       ..
495    11
496     1
497     1
498    10
499    12
Name: date, Length: 500, dtype: int32

In [20]:
df.dtypes

OrderID                   int64
date             datetime64[ns]
region                   object
product                  object
category                 object
customer_type            object
quantity                  int64
price                     int64
discount                float64
sales                   float64
dtype: object

In [21]:
df['quantity'] = df['quantity'].astype(int)
df['price'] = df['price'].astype(float)

In [22]:
df

,OrderID,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590.0,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262.0,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512.0,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485.0,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332.0,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314.0,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369.0,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722.0,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449.0,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869.0,0.09,1581.58

In [23]:
df['region'] = df['region'].str.strip().str.title()

In [24]:
df

,OrderID,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590.0,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262.0,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512.0,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485.0,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332.0,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314.0,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369.0,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722.0,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449.0,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869.0,0.09,1581.58

# Data Analysis Tasks #

In [26]:
df['sales'] = df['price'] * df['quantity']

In [27]:
df

,OrderID,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590.0,0.09,4720.0
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262.0,0.18,524.0
2,3,2024-09-27,North,Phone,Accessories,New,5,512.0,0.09,2560.0
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485.0,0.09,485.0
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332.0,0.22,2324.0
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314.0,0.23,1884.0
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369.0,0.23,3321.0
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722.0,0.14,4332.0
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449.0,0.12,2898.0
499,500,2024-12-01,North,Monitor,Electronics,New,2,869.0,0.09,1738.0

In [28]:
region_sales = df.groupby('region')['sales'].sum()
print(region_sales)

region
East     490986.0
North    607227.0
South    418989.0
West     433493.0
Name: sales, dtype: float64

In [29]:
region_sales.idxmax()

'North'

In [30]:
df.groupby('category')['discount'].mean()

category
Accessories    0.151111
Electronics    0.142744
Name: discount, dtype: float64

In [32]:
top_products = df.groupby('product')['quantity'].sum().sort_values(ascending=False).head(5)

print(top_products)

product
Mouse       481
Laptop      449
Tablet      411
Keyboard    390
Phone       383
Name: quantity, dtype: int64

In [33]:
df['month'] = df['date'].dt.month

In [34]:
df

,OrderID,date,region,product,category,customer_type,quantity,price,discount,sales,month
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590.0,0.09,4720.0,4
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262.0,0.18,524.0,12
2,3,2024-09-27,North,Phone,Accessories,New,5,512.0,0.09,2560.0,9
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485.0,0.09,485.0,4
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332.0,0.22,2324.0,3
...,...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314.0,0.23,1884.0,11
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369.0,0.23,3321.0,1
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722.0,0.14,4332.0,1
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449.0,0.12,2898.0,10
499,500,2024-12-01,North,Monitor,Electronics,New,2,869.0,0.09,1738.0,12

In [35]:
monthly_sales = df.groupby('month')['sales'].sum()

print(monthly_sales)

month
1     112836.0
2     153666.0
3      84870.0
4     176085.0
5     212126.0
6     182172.0
7     148403.0
8     228714.0
9     188593.0
10    150810.0
11    138532.0
12    173888.0
Name: sales, dtype: float64

In [36]:
df['has_discount'] = df['discount'] > 0

In [37]:
df

,OrderID,date,region,product,category,customer_type,quantity,price,discount,sales,month,has_discount
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590.0,0.09,4720.0,4,True
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262.0,0.18,524.0,12,True
2,3,2024-09-27,North,Phone,Accessories,New,5,512.0,0.09,2560.0,9,True
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485.0,0.09,485.0,4,True
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332.0,0.22,2324.0,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314.0,0.23,1884.0,11,True
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369.0,0.23,3321.0,1,True
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722.0,0.14,4332.0,1,True
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449.0,0.12,2898.0,10,True
499,500,2024-12-01,North,Monitor,Electronics,New,2,869.0,0.09,1738.0,12,True

In [38]:
df.groupby('has_discount')['sales'].mean()

has_discount
False    4165.846154
True     3894.330595
Name: sales, dtype: float64

In [39]:
product_sales = df.groupby('product')['sales'].sum()

product_sales.idxmax()

'Laptop'

In [40]:
df.groupby('customer_type')['sales'].sum()

customer_type
New           924784.0
Returning    1025911.0
Name: sales, dtype: float64

In [41]:
df.groupby('customer_type')['sales'].mean()

customer_type
New          3869.389121
Returning    3930.693487
Name: sales, dtype: float64